### ISSUE TITLE
we have error when start backend api

### ISSUE THREAD

**Issue by rmros** [ever-co/ever#844] opened 2019-09-14 13:06 UTC
ramin@server:~/Desktop/project/ever/backend/api$ cd ../..
ramin@server:~/Desktop/project/ever$ yarn run:server
yarn run v1.17.3
$ yarn --cwd ./backend/api start
$ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn tsc && node build/main.js
$ /home/ramin/Desktop/project/ever/backend/api/node_modules/.bin/tsc
src/services/services.app.ts:622:45 - error TS2339: Property 'redirectUrl' does not exist on type 'User'.

622  				res.redirect(baseRedirectUr + req.user.redirectUrl);
     				                                       ~~~~~~~~~~~

src/services/services.app.ts:651:45 - error TS2339: Property 'redirectUrl' does not exist on type 'User'.

651  				res.redirect(baseRedirectUr + req.user.redirectUrl);

**Comment by evereq** [comment] 2019-09-16 17:32
@rmros, we can't reproduce such issues...

Can you please give us an output of the following (running from folder `/backend/api`):
- what OS / version you are using exactly?
- `yarn tsc -v`
- `node -v`
- `dir backend\api\node_modules\passport` (or `ls` of same path if you on Linux)

I would also try to remove all folder `npm_modules` from `/backend/api` and run again `yarn install` from that folder because it looks like Passport package Express extensions are not installed for you for some reason...

**Comment by rmros** [comment] 2019-09-17 21:19
@evereq , its output of following tasks:

ramin@server:~/Desktop/project/ever/backend/api$ node -v
v10.15.0
ramin@server:~/Desktop/project/ever/backend/api$ yarn tsc -v
yarn run v1.17.3
$ /home/ramin/Desktop/project/ever/backend/api/node_modules/.bin/tsc -v
Version 3.4.5
Done in 1.10s.
ramin@server:~/Desktop/project/ever/backend/api$ cd node_modules/
Display all 1314 possibilities? (y or n)^C
ramin@server:~/Desktop/project/ever/backend/api$ cd node_modules/passport
ramin@server:~/Desktop/project/ever/backend/api/node_modules/passport$ ls
lib  LICENSE  package.json  README.md
ramin@server:~/Desktop/project/ever/backend/api/node_modules/passport$ cd lib
ramin@server:~/Desktop/project/ever/backend/api/node_modules/passport/lib$ ll
total 52
drwxr-xr-x 7 ramin ramin  4096 Sep 13 15:19 ./
drwxr-xr-x 3 ramin ramin  4096 Sep 13 15:19 ../
-rw-r--r-- 1 ramin ramin 13429 Sep 13 10:35 authenticator.js
drwxr-xr-x 2 ramin ramin  4096 Sep 13 15:19 errors/
drwxr-xr-x 2 ramin ramin  4096 Sep 13 15:19 framework/
drwxr-xr-x 2 ramin ramin  4096 Sep 13 15:19 http/
-rw-r--r-- 1 ramin ramin   474 Sep 13 10:35 index.js
drwxr-xr-x 2 ramin ramin  4096 Sep 13 15:19 middleware/
-rw-r--r-- 1 ramin ramin   867 Sep 13 10:35 sessionmanager.js
drwxr-xr-x 2 ramin ramin  4096 Sep 13 15:19 strategies/

**Comment by rmros** [comment] 2019-09-17 22:08
```
ramin@server:~/Desktop/project/ever/backend/api$ rm -rf node_modules/
ramin@server:~/Desktop/project/ever/backend/api$ yarn install
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @nestjs/cqrs@6.0.1" has incorrect peer dependency "reflect-metadata@0.1.12".
warning "@nestjs/graphql > merge-graphql-schemas > graphql-toolkit@0.5.0" has unmet peer dependency "graphql-tag-pluck@^0.8.3".
warning " > @commitlint/config-lerna-scopes@8.1.0" has unmet peer dependency "lerna@^3.0.0".
warning " > webpack-graphql-loader@1.0.2" has incorrect peer dependency "ts-loader@^4.4.1".
[5/5] Building fresh packages...
$ yarn run snyk-protect
yarn run v1.17.3
$ yarn snyk protect
$ /home/ramin/Desktop/project/ever/backend/api/node_modules/.bin/snyk protect
| Analyzing yarn dependencies for api project dir
Successfully applied Snyk patches

Done in 171.89s.
Done in 200.88s.
ramin@server:~/Desktop/project/ever/backend/api$ 
ramin@server:~/Desktop/project/ever/backend/api$ yarn start
yarn run v1.17.3
$ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn tsc && node build/main.js
$ /home/ramin/Desktop/project/ever/backend/api/node_modules/.bin/tsc
src/services/services.app.ts:622:45 - error TS2339: Property 'redirectUrl' does not exist on type 'User'.

622  				res.redirect(baseRedirectUr + req.user.redirectUrl);
     				                                       ~~~~~~~~~~~

src/services/services.app.ts:651:45 - error TS2339: Property 'redirectUrl' does not exist on type 'User'.

651  				res.redirect(baseRedirectUr + req.user.redirectUrl);
     				                                       ~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ramin@server:~/Desktop/project/ever/backend/api$ 

```

**Comment by evereq** [comment] 2019-09-19 19:47
@rmros Can you try to comment out that lines where you see errors and try to run again?
An alternative is to try to do it like `req.user["redirectUrl"]`
_(this is not an essential code used for authenticating with FB / Google)_
Just want to isolate the issue and make sure other code does not have similar problems...
Let us know if it helps, please.

**Comment by evereq** [comment] 2019-12-13 16:18
Implemented possible fix with https://github.com/ever-co/ever/commit/8f0772fa8d1d3555a423356961a63ab135455876, closing ticket

**Closed by evereq** 2019-12-13 16:18 UTC
Labels: needs-more-detail
