### ISSUE TITLE
Admin: completed orders and revenue not loaded

### ISSUE THREAD

**Issue by tsvetelina-e-y** [ever-co/ever#1125] opened 2020-06-19 13:10 UTC
On Dashboard completed orders and revenue information is not loaded when no store selected
![image](https://user-images.githubusercontent.com/49713089/85135737-4186d900-b247-11ea-93ff-525d85c328a7.png)

**Comment by valiopld** [comment] 2020-07-13 08:27
![image](https://user-images.githubusercontent.com/52473395/87281128-942c7b80-c4fb-11ea-9eff-1e3d573515b9.png)
everything works fine

**Comment by evereq** [comment] 2020-07-13 08:51
@valiopld I think for you it works fine because DB is empty, please try to run "Fake data generator" (available in Setup menu I think) and wait till DB get full and test that page again

**Comment by valiopld** [comment] 2020-07-13 09:15
@evereq 
after "Fake data generator" its still working fine for me.
![image](https://user-images.githubusercontent.com/52473395/87287023-449d7e00-c502-11ea-8415-cda803d6e797.png)

**Comment by evereq** [comment] 2020-07-13 09:31
@valiopld I don't think you generated ALL fake data (probably you click on wrong button), because with fake data should be like thousands of orders in DB (not one0 and millions of $ in revenue etc.

**Comment by valiopld** [comment] 2020-07-13 13:05
@evereq 
I think the reason that not full data was generated is becouse "Fake data genrator" is broken *for me* (some errors are displayed before full generation is complete) 
However, I successfully generated almost everything and its still working 
If you think the problem is because not full data was generated I can try to fix "fake generator" and to try again

![image](https://user-images.githubusercontent.com/52473395/87307627-9e15a500-c522-11ea-92f3-fe1bc9cffa21.png)

**Comment by evereq** [comment] 2020-07-13 13:22
@valiopld yes please review fake data generator and see if you can / should fix it. Make sure you killed DB and so it recreate it all from 0, because it might happen that you have issues with fake data generator if you run it not first time with same DB

**Comment by valiopld** [comment] 2020-07-14 06:38
@evereq 
I tried many times to generate data and track where the data generation error is, but each time a different error was displayed (most of them with promises). 
*Every time kill DB and recreate it

However, sometimes data is generated completely without error (very very rarely) and "Today's completed orders " & "Today's Revenue" still  work fine.
To keep looking for the problem, I need exactly what error is displayed in the console (if any)

Some of the showing errors whith "the fake data generator" 
![image](https://user-images.githubusercontent.com/52473395/87392352-0a40e900-c5b5-11ea-8d68-aff511f2e8d6.png)
![image](https://user-images.githubusercontent.com/52473395/87392380-15941480-c5b5-11ea-8deb-585d591f6329.png)
![image](https://user-images.githubusercontent.com/52473395/87392394-1cbb2280-c5b5-11ea-92e6-c1578b9f6aa0.png)

**Comment by evereq** [comment] 2020-07-14 07:07
@valiopld ok, so one of error seems related to how we generate fake devices or something related to them (key too large to index), others I am not sure. But lets for now close this ticket, basically what you are saying is that fake data generator did not work well for you (fails randomly), but dashboard works all the time, so most probably issue with dashboard already fixed by other commits.  Don't waste time on fake data generator please, we will refactor it and move it to the server (where it belongs) later

**Closed by evereq** 2020-07-14 07:07 UTC
Labels: type: bug :bug:
